import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [courses, setCourses] = useState([])
  const [gpa, setGpa] = useState(0)
  const [courseId, setCourseId] = useState(0)

  function addCourse() {
    let course = (
      <tr key={courseId}>
        <td>
          <input type="number" name={`unit${courseId}`} className="form-control" defaultValue="3" />
        </td>
        <td>
          <input type="number" step="0.5" name={`grade${courseId}`} className="form-control" defaultValue="0.0" />
        </td>
        {/* <td>
          <button type="button" className="btn btn-outline-danger">
            <i className="fas fa-trash" aria-hidden="true"></i>
          </button>
        </td> */}
      </tr>
    )    

    setCourses([...courses, course])
    setCourseId(courseId + 1)
  }

  function removeCourse() {
    let newCourses = [...courses]
    newCourses.pop()

    setCourses([...newCourses])
  }

  function calculate(event) {
    event.preventDefault()

    let totalUnits = 0
    let gradesEarned = 0


    for (let i  = 0; i < courseId; i++) {
      try {
        let units = parseInt(event.target.elements[`unit${i}`].value)
        let grade = parseFloat(event.target.elements[`grade${i}`].value)

        totalUnits += units
        gradesEarned += units * grade
        

      } catch (e) {}
    }

    setGpa(gradesEarned / totalUnits)

  }

  return (
    <>
      <Head>
        <title>DLSU GPA Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <form className="container table-container" onSubmit={calculate}>
        <table className="table border rounded-3">
          <thead>
            <tr>
              <th scope="col">Units</th>
              <th scope="col">Grade</th>
              {/* <th scope="col"></th> */}
            </tr>
          </thead>
          <tbody id="courses-table">
            {courses}
          </tbody>
        </table>

        <div className="btn-group mb-3">
          <button type="button" className="btn border" onClick={addCourse}>
            <i className="fas fa-plus"></i>
          </button>
          <button type="button" className="btn border" onClick={removeCourse}>
            <i className="fas fa-minus"></i>
          </button>
        </div>

        <div className="mb-3">
          <p id="gpa-display" className="h4">GPA: {gpa.toFixed(3)}</p>
        </div>

        <div>
          <input type="submit" value="Calculate" className="btn btn-primary" />
        </div>
      </form>
    </>
  )
}
